### ISSUE TITLE
Ezeket az adatokat nem tudom értelmezni

### ISSUE THREAD

**Issue by PstasDev** [zal1000/reggeltbot#117]
Az r!count parancs után az embedben több szám is látható viszont felirat hogy mi mit jelent az nincs. Kép csatolva
![IMG_20210405_074644](https://user-images.githubusercontent.com/60182573/113541890-66381b80-95e3-11eb-8ed3-663cc7541b24.jpg)

**Comment by orozso** [comment]
Szia @BallaBotond!

Köszönjük a issue-t, javítva lett a leírt hiba. Hamarosan majd megjelenik a relaese-ben is.
![image](https://user-images.githubusercontent.com/12803062/113558557-26336180-9600-11eb-9ffe-aeeef0452fe6.png)

**Comment by orozso** [comment]
Jövőbéli problémák merültek fel, ezért visszavontuk a commitot, az issue-t megnyitotuk.

**Comment by zal1000** [comment]
@BallaBotond Elvilg ki lett javítva, ha bármi más hibával találkozol akkor megköszönnénk egy újabb issuet!
