### ISSUE TITLE
Nem szeret mindenkit a bot

### ISSUE THREAD

**Issue by PstasDev** [zal1000/reggeltbot#120]
A mai nap újra előfordult hogy egyes embereket nem érzékel ott a bot. Ha mást írnak be, nem törli ki, illetve nem reagál a reggelt üzenetre míg például az enyémre igen. Nekem kitörli a másik üzeneteket. A counter nekik továbbra is nullát mutat.
![IMG_20210406_091838](https://user-images.githubusercontent.com/60182573/113674511-8c7cba80-96ba-11eb-9882-1042e06dcb4d.jpg)

**Comment by orozso** [comment]
Szia @BallaBotond!

Köszönjük a issue-t, ismerjük a hibát, a bot néhány percre elmegy sziesztára. Az offline bot semmire nem tud reagálni.
Ezen hiba nem a fejlesztésből, hanem üzemeltetésből vérzik.
