### ISSUE TITLE
Teljesen véletlenszerű ébrenlét

### ISSUE THREAD

**Issue by PstasDev** [zal1000/reggeltbot#125]
Másodpercenként változik hogy a bot reagál e az üzeneteinkre, és ezt a reggelt csatornán meg tudtuk diskurálni mert nem figyelt. Nem tudom hogy ez a hiba honnan ered, lehet hogy az üzemeltetésből, de azért gondoltam jelentem

**Comment by zal1000** [comment]
Szerintem a hozzákapcsolt pull request-ben ki van javítva, ha nem akkor újra megbyitom az issue-t
