### ISSUE TITLE
It is possible to get negative amounts of coins

### ISSUE THREAD

**Issue by zsotroav** [zal1000/reggeltbot#130]
**EN:** 
**Feature:** If you send a message to the channel without `reggelt`/`morning` you lose a coin.
**Expected result:** Coins stay at 0
**Actual result:** Coins go into the negatives

**HU:**
**Funkció:** Ha üzenetet küldesz a reggelt csatornára `reggelt` nélkül akkor elveszítesz egy coint
**Várt eredmény:** 0 coin marad
**Tényleges eredmény:** A coin száma lemegy a negatívokba

![Untitled](https://user-images.githubusercontent.com/49715074/124268508-e1a15e80-db39-11eb-8039-1c1f63dee13d.png)

**Comment by zal1000** [comment]
Its not a bug, its a feature
